### ISSUE TITLE
Keybind customization doesn't exist in any capacity, input system overall could use a rework

### ISSUE THREAD

**Issue by jackwright-ual** [Warlander/DeedPlanner-3#19]
An implementation of a key bind interface is required using either Unity's UI or by code.

**Comment by Warlander** [comment]
DeedPlanner is now using new Unity input system, so adding customizable keybinds should be much easier to do than in the past. Current inputs are also relative to position of keys on the keyboard instead of being fixed, so by default for example WASD movement will still be used the same physical positions of keys under different layouts like AZERTY.

**Comment by Warlander** [comment]
Feature done.
